---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# paratests

<!-- badges: start -->
<!-- badges: end -->

The goal of paratests is to make performing (non-)parametric tests in R easier and more reproducible. Today this package contains four functions:

* __anova()__: print the p value of an analysis of variance summary
* __cor_scatterplot()__: scatterplot of variables and their correlation test coefficient and p value
* __mean_barchart()__: barchart of a variable mean and standard deviation per group
* __sw_tidy()__: print the p value of a Shapiro Wilk normality test

Every function has to be performed on a tidy dataset.

## Installation

Paratests depends on the following packages, make sure these are installed first:

``` r
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("magrittr")
# install.packages("palmerpenguins")
# install.packages("stats")
```

You can then install and use the the most recent version of paratests from this GitHub with:

``` r
devtools::install_github("stephaniedewit/paratests")
library(paratests)
```

## Examples

For an example of each function use `?anova()`, `?cor_scatterplot()`, `?mean_barchart()` and `?sw_tidy`. For a vignette with a short analysis combining the four functions use `browseVignettes("paratests")`. 

To try for yourself, two example datasets can be loaded into the Environment with `data(PlantGrowth_edit)` and `data(potato)`.
