#' Plant growth data edited with heigth and leafs values
#'
#' Dummy data generated by my DSFB2 teachers, to which I added height and leaf values so this data can be used as an universal function example
#'
#' @docType data
#'
#' @usage data(PlantGrowth_edit)
#'
#' @format An Rds table file
#'
#' @keywords datasets
#'
#' @references ...
#'
#' @source ...
#'
#' @examples
#' data(PlantGrowth_edit)
#' cor_scatterplot(PlantGrowth_edit, PlantGrowth_edit$leafs, PlantGrowth_edit$height, reposition_r = 3)
"PlantGrowth_edit"
