#' Potato data
#'
#' Dummy data generated by my DSFB2 teachers. It contains the sodium contents for four groups of chips.
#'
#' @docType data
#'
#' @usage data(potato)
#'
#' @format An Rds table file
#'
#' @keywords datasets
#'
#' @references ...
#'
#' @source ...
#'
#' @examples
#' data(potato)
#' anova(potato$Natrium, potato$Groep)
"potato"
